services:
  devcontainer:
    build:
      dockerfile: Containerfile
    volumes:
      - ../:/workspace
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 20000
    entrypoint: tail -f /dev/null